name: git-ijohnson
version: 2.19.0
summary: Git is a free and open source distributed version control system.
description: This example is not really production quality
grade: stable
confinement: strict
apps:
  git:
    command: git
    environment:
      GIT_TEMPLATE_DIR: $SNAP/share/git-core/templates
      GIT_CONFIG_NOSYSTEM: "true"
      GIT_EXEC_PATH: $SNAP/libexec/git-core
      GIT_TEXTDOMAINDIR: $SNAP/usr/share/locale

parts:
  git:
    source: https://github.com/git/git
    source-type: git
    source-tag: v2.19.0
    source-depth: 1
    plugin: autotools
    configflags:
      - --with-curl
      - --with-expat
    build-packages:
        - gettext
        - libssl-dev
        - libexpat1-dev
    stage-packages:
        - gettext
        - libcurl4-openssl-dev
